### ISSUE TITLE
Strange behavior with new Voicemail event

### ISSUE THREAD

**Issue by grokify** [tylerlong/ringcentral-python#2]
When receiving an event where `changes` = `[{"type":"VoiceMail","newCount":1,"updatedCount":0}]` (and not for SMS, calls, etc.), it seems the message string has non-printable characters appended to the end.

For example, the following `message` string (using the `README.md` example) has a visible length of 362 but `len(message)` will report 368:

```json
{"uuid":"1111111111111111111-2222222222222222222","event":"/restapi/v1.0/account/111111111/extension/222222222/message-store","timestamp":"2017-03-26T15:14:08.357Z","subscriptionId":"11112222-3333-4444-5555-666677778888","body":{"extensionId":222222222,"lastUpdated":"2017-03-26T15:13:57.572+0000","changes":[{"type":"VoiceMail","newCount":1,"updatedCount":0}]}}
```

This results in the following error using `json.loads(message)`:

`take message interrupted: Extra data: line 1 column 362 (char 361)`

The following workaround will resolve the issue and allow the string to be parsed by `json`:

```python
import re
message = re.sub(r"}[^}]+$","}", message)
```

Not sure where these extra characters are being added at this point.

**Comment by tylerlong** [comment]
This is indeed strange. I tested fax and sms and couldn't reproduce this issue.

Let me test some voice mail later

**Comment by tylerlong** [comment]
Can you reproduce this issue with other SDKs?
